version: '3.7'

x-defaults: &defaults
  image: ethibox/ethibox:${VERSION:-latest}
  volumes:
    - ${VOLUME_PATH}data:/app/prisma:cached
  environment:
    # - PREFIX_PATH=/app
    - NODE_ENV=production
    - MYSQL_DATABASE=ethibox
    - MYSQL_USER=ethibox
    - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    - MYSQL_HOST=mariadb
    - PORTAINER_ENDPOINT=${PORTAINER_ENDPOINT:-http://portainer.localhost}
    - PORTAINER_USERNAME=${PORTAINER_USERNAME:-admin}
    - PORTAINER_PASSWORD=${PORTAINER_PASSWORD:-myp@ssw0rd}
    - MAIL_HOST=${MAIL_HOST}
    - MAIL_USER=${MAIL_USER}
    - MAIL_PASS=${MAIL_PASS}
    - SECRET=${SECRET}

services:
  web:
    <<: *defaults
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ethibox-${NUMBER:-1}.rule=Host(`${DOMAIN:-ethibox.localhost}`)
        - traefik.http.routers.ethibox-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.ethibox-${NUMBER:-1}.service=ethibox-${NUMBER:-1}
        - traefik.http.routers.ethibox-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.ethibox-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

  cron:
    <<: *defaults
    command: node cron.js
    networks:
      - internal

  # metrics:
    # <<: *defaults
    # command: node metrics.js
    # networks:
      # - internal
      # - traefik

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - MYSQL_DATABASE=ethibox
      - MYSQL_USER=ethibox
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    networks:
      - internal

volumes:
  mariadb:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
